openapi: 3.2.0
info:
  title: Level2 Hub Controller Update Live Deployment Flag API
  version: 0.1.0
tags:
- name: Update Live Deployment Flag
paths:
  /update_live_deployment_flag:
    post:
      summary: Update Live Deployment Flag
      operationId: update_live_deployment_flag_update_live_deployment_flag_post
      parameters:
      - required: true
        schema:
          title: Deployment Id
          type: integer
        name: deployment_id
        in: query
      - required: true
        schema:
          title: Flag
          type: string
        name: flag
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Update Live Deployment Flag
components:
  schemas:
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
