openapi: 3.2.0
info:
  title: Level2 Hub Controller Get Strategy Library API
  version: 0.1.0
tags:
- name: Get Strategy Library
paths:
  /get_strategy_library:
    get:
      summary: Get Strategy Library
      operationId: get_strategy_library_get_strategy_library_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Strategy Library Get Strategy Library Get
                type: array
                items:
                  $ref: '#/components/schemas/StrategyLibraryOut'
      tags:
      - Get Strategy Library
components:
  schemas:
    StrategyLibraryOut:
      title: StrategyLibraryOut
      type: object
      properties:
        id:
          title: Id
          type: integer
        strategy_name:
          title: Strategy Name
          type: string
        keygen:
          title: Keygen
          type: string
        strategy_data:
          title: Strategy Data
          type: string
        canvas_data:
          title: Canvas Data
          type: string
