openapi: 3.2.0
info:
  title: Level2 Hub Controller Get Showcase Videos API
  version: 0.1.0
tags:
- name: Get Showcase Videos
paths:
  /get_showcase_videos:
    get:
      summary: Get Showcase Videos
      operationId: get_showcase_videos_get_showcase_videos_get
      parameters:
      - required: false
        schema:
          title: Source
          type: string
        name: source
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Showcase Videos Get Showcase Videos Get
                type: array
                items:
                  $ref: '#/components/schemas/ShowcaseOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Get Showcase Videos
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    ShowcaseOut:
      title: ShowcaseOut
      required:
      - description
      - link
      - image_path
      - is_valid
      - label
      type: object
      properties:
        description:
          title: Description
          type: string
        link:
          title: Link
          type: string
        image_path:
          title: Image Path
          type: string
        is_valid:
          title: Is Valid
          type: boolean
        label:
          title: Label
          type: string
        created_at:
          title: Created At
          type: string
          format: date-time
