openapi: 3.2.0
info:
  title: Level2 Hub Controller Get Symbol Data V2 API
  version: 0.1.0
tags:
- name: Get Symbol Data V2
paths:
  /get_symbol_data_v2:
    get:
      summary: Get Symbol Data V2
      operationId: get_symbol_data_v2_get_symbol_data_v2_get
      parameters:
      - required: true
        schema:
          title: Ticker
          type: string
        name: ticker
        in: query
      - required: false
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Get Symbol Data V2
components:
  schemas:
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
