openapi: 3.2.0
info:
  title: Level2 Hub Controller Canvas Get Pair Trading API
  version: 0.1.0
tags:
- name: Canvas Get Pair Trading
paths:
  /canvas_get_pair_trading:
    get:
      summary: Canvas Get Pair Trading
      operationId: canvas_get_pair_trading_canvas_get_pair_trading_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Canvas Get Pair Trading
