openapi: 3.2.0
info:
  title: Level2 Hub Controller Send Otp Password Reset API
  version: 0.1.0
tags:
- name: Send Otp Password Reset
paths:
  /send_otp_password_reset:
    post:
      summary: Send Otp Password Reset
      operationId: send_otp_password_reset_send_otp_password_reset_post
      parameters:
      - required: true
        schema:
          title: Email
          type: string
        name: email
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Send Otp Password Reset
components:
  schemas:
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
