openapi: 3.2.0
info:
  title: Level2 Hub Controller Undeploy Live Deployment API
  version: 0.1.0
tags:
- name: Undeploy Live Deployment
paths:
  /undeploy_live_deployment:
    get:
      summary: Undeploy Live Deployment
      operationId: undeploy_live_deployment_undeploy_live_deployment_get
      parameters:
      - required: true
        schema:
          title: Deployment Id
          type: integer
        name: deployment_id
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Undeploy Live Deployment Undeploy Live Deployment Get
                type: array
                items:
                  $ref: '#/components/schemas/LiveActiveDeploymentsOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Undeploy Live Deployment
components:
  schemas:
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    StrategyOut:
      title: StrategyOut
      required:
      - id
      - keygen
      - backtest_type
      type: object
      properties:
        id:
          title: Id
          type: integer
        keygen:
          title: Keygen
          type: string
        strategy_name:
          title: Strategy Name
          type: string
        symbol:
          title: Symbol
          type: string
        is_deleted:
          title: Is Deleted
          type: integer
          default: 0
        timeframe:
          title: Timeframe
          type: string
        strategy_category:
          $ref: '#/components/schemas/StrategyCategoryOut'
        add_ons:
          title: Add Ons
          type: string
        broker_id:
          title: Broker Id
          type: integer
        is_copied:
          title: Is Copied
          type: integer
          default: 0
        is_notification:
          title: Is Notification
          type: integer
          default: 0
        backtest_type:
          title: Backtest Type
          type: string
        strategy_data:
          title: Strategy Data
          type: string
        canvas_data:
          title: Canvas Data
          type: string
        strategy_description:
          title: Strategy Description
          type: string
        created_at:
          title: Created At
          type: string
          format: date-time
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    B2cBrokersOut:
      title: B2cBrokersOut
      type: object
      properties:
        id:
          title: Id
          type: integer
        broker_name:
          title: Broker Name
          type: string
        image_url:
          title: Image Url
          type: string
        doc_url:
          title: Doc Url
          type: string
        referral_link:
          title: Referral Link
          type: string
        offer_valid:
          title: Offer Valid
          type: integer
    LiveActiveDeploymentsOut:
      title: LiveActiveDeploymentsOut
      required:
      - deployment_meta
      - deployment_id
      - strategy_key
      - strategy_name
      - strategy_data
      - user_id
      type: object
      properties:
        deployment_meta:
          $ref: '#/components/schemas/LiveDeploymentOut'
        deployment_id:
          title: Deployment Id
          type: integer
        strategy_key:
          title: Strategy Key
          type: string
        strategy_name:
          title: Strategy Name
          type: string
        strategy_data:
          title: Strategy Data
          type: string
        depl_flag:
          title: Depl Flag
          type: string
        order_trade_type:
          title: Order Trade Type
          type: string
        meta_data:
          title: Meta Data
          type: string
        user_id:
          title: User Id
          type: integer
    StrategyCategoryOut:
      title: StrategyCategoryOut
      required:
      - id
      - label
      - description
      - is_valid
      type: object
      properties:
        id:
          title: Id
          type: integer
        label:
          title: Label
          type: string
        description:
          title: Description
          type: string
        is_valid:
          title: Is Valid
          type: string
    LiveDeploymentOut:
      title: LiveDeploymentOut
      required:
      - created_at
      - last_updated_at
      - broker
      - strategy
      type: object
      properties:
        id:
          title: Id
          type: integer
        meta_data:
          title: Meta Data
          type: string
        dep_flag:
          title: Dep Flag
          type: string
        is_valid:
          title: Is Valid
          type: string
        deployed_symbols:
          title: Deployed Symbols
          type: string
        order_trade_type:
          title: Order Trade Type
          type: string
        created_at:
          title: Created At
          type: string
          format: date-time
        last_updated_at:
          title: Last Updated At
          type: string
          format: date-time
        broker:
          $ref: '#/components/schemas/B2cBrokersOut'
        strategy:
          $ref: '#/components/schemas/StrategyOut'
