openapi: 3.2.0
info:
  title: Level2 Hub Controller Create Market Scanner Universe API
  version: 0.1.0
tags:
- name: Create Market Scanner Universe
paths:
  /create_market_scanner_universe:
    post:
      summary: Create Market Scanner Universe
      operationId: create_market_scanner_universe_create_market_scanner_universe_post
      parameters:
      - required: true
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      - required: true
        schema:
          title: Name
          type: string
        name: name
        in: query
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_create_market_scanner_universe_create_market_scanner_universe_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketScannerUniverseOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Create Market Scanner Universe
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    MarketScannerUniverseOut:
      title: MarketScannerUniverseOut
      type: object
      properties:
        meta:
          title: Meta
          type: object
        keygen:
          title: Keygen
          type: string
        universe_list:
          title: Universe List
          type: array
          items: {}
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_create_market_scanner_universe_create_market_scanner_universe_post:
      title: Body_create_market_scanner_universe_create_market_scanner_universe_post
      type: object
      properties:
        stocks_list:
          title: Stocks List
          type: string
