openapi: 3.2.0
info:
  title: Level2 Hub Controller Ctrader Access API
  version: 0.1.0
tags:
- name: Ctrader Access
paths:
  /ctrader_access:
    get:
      summary: Ctrader Access
      operationId: ctrader_access_ctrader_access_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Ctrader Access
