openapi: 3.2.0
info:
  title: Level2 Hub Controller Get Earnings Calendar API
  version: 0.1.0
tags:
- name: Get Earnings Calendar
paths:
  /get_earnings_calendar:
    get:
      summary: Get Earnings Calendar
      operationId: get_earnings_calendar_get_earnings_calendar_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Get Earnings Calendar
