openapi: 3.2.0
info:
  title: Level2 Hub Controller Test Twitter API
  version: 0.1.0
tags:
- name: Test Twitter
paths:
  /test_twitter:
    get:
      summary: Test Twitter
      operationId: test_twitter_test_twitter_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Test Twitter
