openapi: 3.2.0
info:
  title: Level2 Hub Controller Marketplace Recent Trades API
  version: 0.1.0
tags:
- name: Marketplace Recent Trades
paths:
  /marketplace_recent_trades:
    get:
      summary: Marketplace Recent Trades
      operationId: marketplace_recent_trades_marketplace_recent_trades_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Marketplace Recent Trades
