openapi: 3.2.0
info:
  title: Level2 Hub Controller Build New Strategy API
  version: 0.1.0
tags:
- name: Build New Strategy
paths:
  /build_new_strategy:
    post:
      summary: Build New Strategy
      operationId: build_new_strategy_build_new_strategy_post
      parameters:
      - required: true
        schema:
          title: Symbol
          type: string
        name: symbol
        in: query
      - required: true
        schema:
          title: Timeframe
          type: string
        name: timeframe
        in: query
      - required: true
        schema:
          title: Strategy Name
          type: string
        name: strategy_name
        in: query
      - required: true
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      - required: false
        schema:
          title: Broker Id
          type: integer
        name: broker_id
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StrategyPrefCustomOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Build New Strategy
components:
  schemas:
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    StrategyOut:
      title: StrategyOut
      required:
      - id
      - keygen
      - backtest_type
      type: object
      properties:
        id:
          title: Id
          type: integer
        keygen:
          title: Keygen
          type: string
        strategy_name:
          title: Strategy Name
          type: string
        symbol:
          title: Symbol
          type: string
        is_deleted:
          title: Is Deleted
          type: integer
          default: 0
        timeframe:
          title: Timeframe
          type: string
        strategy_category:
          $ref: '#/components/schemas/StrategyCategoryOut'
        add_ons:
          title: Add Ons
          type: string
        broker_id:
          title: Broker Id
          type: integer
        is_copied:
          title: Is Copied
          type: integer
          default: 0
        is_notification:
          title: Is Notification
          type: integer
          default: 0
        backtest_type:
          title: Backtest Type
          type: string
        strategy_data:
          title: Strategy Data
          type: string
        canvas_data:
          title: Canvas Data
          type: string
        strategy_description:
          title: Strategy Description
          type: string
        created_at:
          title: Created At
          type: string
          format: date-time
    UserPreferenceOut:
      title: UserPreferenceOut
      type: object
      properties:
        country:
          title: Country
          type: string
        trading_yoe:
          title: Trading Yoe
          type: string
        risk_class:
          title: Risk Class
          type: string
        language:
          title: Language
          type: string
        asset_class:
          title: Asset Class
          type: string
        notification_preference:
          title: Notification Preference
          type: string
        nudges_tracker:
          title: Nudges Tracker
          type: string
        walkthrough_status:
          title: Walkthrough Status
          type: string
        webhook:
          title: Webhook
          type: string
        send_email:
          title: Send Email
          type: string
        socials:
          title: Socials
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    StrategyPrefCustomOut:
      title: StrategyPrefCustomOut
      required:
      - strategy
      - meta
      type: object
      properties:
        strategy:
          $ref: '#/components/schemas/StrategyOut'
        broker_id:
          title: Broker Id
          type: integer
        meta:
          $ref: '#/components/schemas/UserPreferenceOut'
    StrategyCategoryOut:
      title: StrategyCategoryOut
      required:
      - id
      - label
      - description
      - is_valid
      type: object
      properties:
        id:
          title: Id
          type: integer
        label:
          title: Label
          type: string
        description:
          title: Description
          type: string
        is_valid:
          title: Is Valid
          type: string
