openapi: 3.2.0
info:
  title: Level2 Hub Controller Unlok Util APIs API
  version: 0.1.0
tags:
- name: Unlok Util APIs
paths:
  /unlok/generate_token:
    post:
      tags:
      - Unlok Util APIs
      summary: Generate Unlok Token
      operationId: generate_unlok_token_unlok_generate_token_post
      parameters:
      - required: false
        schema:
          title: Account Id
          type: string
        name: account_id
        in: query
      - required: false
        schema:
          title: Server Id
          type: integer
        name: server_id
        in: query
      - required: false
        schema:
          title: Broker Sub Domain
          type: string
        name: broker_sub_domain
        in: query
      - required: false
        schema:
          title: Support Email
          type: string
        name: support_email
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /unlok/auth:
    post:
      tags:
      - Unlok Util APIs
      summary: Unlok Auth
      operationId: unlok_auth_unlok_auth_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
