openapi: 3.2.0
info:
  title: Level2 Hub Controller Accounts API
  version: 0.1.0
tags:
- name: Accounts
paths:
  /accounts/sterling:
    get:
      summary: Get Sterling Accounts
      operationId: get_sterling_accounts_accounts_sterling_get
      parameters:
      - required: false
        schema:
          title: Token
          type: string
        name: token
        in: query
      - required: false
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Accounts
  /accounts/connecttrade:
    get:
      summary: Get Connecttrade Accounts
      operationId: get_connecttrade_accounts_accounts_connecttrade_get
      parameters:
      - required: false
        schema:
          title: Accounts Uuid
          type: string
        name: accounts_uuid
        in: query
      - required: false
        schema:
          title: Broker Id
          type: integer
        name: broker_id
        in: query
      - required: false
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Accounts
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
