openapi: 3.2.0
info:
  title: Level2 Hub Controller Submit Email For Video API
  version: 0.1.0
tags:
- name: Submit Email For Video
paths:
  /submit_email_for_video:
    get:
      summary: Submit Email For Video
      operationId: submit_email_for_video_submit_email_for_video_get
      parameters:
      - required: true
        schema:
          title: Email
          type: string
        name: email
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Submit Email For Video
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
