openapi: 3.2.0
info:
  title: Level2 Hub Controller Reset Broker Configuration API
  version: 0.1.0
tags:
- name: Reset Broker Configuration
paths:
  /reset_broker_configuration:
    post:
      summary: Reset Broker Configuration
      operationId: reset_broker_configuration_reset_broker_configuration_post
      parameters:
      - required: true
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      - required: true
        schema:
          title: Broker Id
          type: integer
        name: broker_id
        in: query
      - required: false
        schema:
          title: Connection Id
          type: integer
        name: connection_id
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Reset Broker Configuration
components:
  schemas:
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
