openapi: 3.2.0
info:
  title: Level2 Hub Controller Get Ticker Data V2 API
  version: 0.1.0
tags:
- name: Get Ticker Data V2
paths:
  /get_ticker_data_v2:
    get:
      summary: Get Ticker Data V2
      operationId: get_ticker_data_v2_get_ticker_data_v2_get
      parameters:
      - required: true
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      - required: true
        schema:
          title: Ticker
          type: string
        name: ticker
        in: query
      - required: true
        schema:
          title: Timestamp
          type: string
        name: timestamp
        in: query
      - required: false
        schema:
          title: Broker Id
          type: integer
        name: broker_id
        in: query
      - required: false
        schema:
          title: Limit
          type: integer
        name: limit
        in: query
      - required: false
        schema:
          title: Strategy Id
          type: string
        name: strategy_id
        in: query
      - required: false
        schema:
          title: Request Type
          type: string
        name: request_type
        in: query
      - required: false
        schema:
          title: Start
          type: string
        name: start
        in: query
      - required: false
        schema:
          title: End Date
          type: string
        name: end_date
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Get Ticker Data V2
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
