openapi: 3.2.0
info:
  title: Level2 Hub Controller Get Strategy Categories API
  version: 0.1.0
tags:
- name: Get Strategy Categories
paths:
  /get_strategy_categories:
    get:
      summary: Get Strategy Categories
      operationId: get_strategy_categories_get_strategy_categories_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Strategy Categories Get Strategy Categories Get
                type: array
                items:
                  $ref: '#/components/schemas/StrategyCategoryOut'
      tags:
      - Get Strategy Categories
components:
  schemas:
    StrategyCategoryOut:
      title: StrategyCategoryOut
      required:
      - id
      - label
      - description
      - is_valid
      type: object
      properties:
        id:
          title: Id
          type: integer
        label:
          title: Label
          type: string
        description:
          title: Description
          type: string
        is_valid:
          title: Is Valid
          type: string
