openapi: 3.2.0
info:
  title: Level2 Hub Controller Copy User Strategy API
  version: 0.1.0
tags:
- name: Copy User Strategy
paths:
  /copy_user_strategy:
    get:
      summary: Copy User Strategy
      operationId: copy_user_strategy_copy_user_strategy_get
      parameters:
      - required: true
        schema:
          title: User Id
          type: string
        name: user_id
        in: query
      - required: true
        schema:
          title: Keygen Original
          type: string
        name: keygen_original
        in: query
      - required: true
        schema:
          title: Keygen Current
          type: string
        name: keygen_current
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Copy User Strategy
components:
  schemas:
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
