openapi: 3.2.0
info:
  title: Level2 Hub Controller Verify User API
  version: 0.1.0
tags:
- name: Verify User
paths:
  /verify_user:
    post:
      summary: Verify User
      operationId: verify_user_verify_user_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCustomOut'
      tags:
      - Verify User
components:
  schemas:
    UserPreferenceOut:
      title: UserPreferenceOut
      type: object
      properties:
        country:
          title: Country
          type: string
        trading_yoe:
          title: Trading Yoe
          type: string
        risk_class:
          title: Risk Class
          type: string
        language:
          title: Language
          type: string
        asset_class:
          title: Asset Class
          type: string
        notification_preference:
          title: Notification Preference
          type: string
        nudges_tracker:
          title: Nudges Tracker
          type: string
        walkthrough_status:
          title: Walkthrough Status
          type: string
        webhook:
          title: Webhook
          type: string
        send_email:
          title: Send Email
          type: string
        socials:
          title: Socials
          type: string
    UserCustomOut:
      title: UserCustomOut
      required:
      - user
      - preference
      - user_id
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserOut'
        preference:
          $ref: '#/components/schemas/UserPreferenceOut'
        broker_meta:
          title: Broker Meta
          type: object
        meta_data:
          title: Meta Data
          type: string
        is_old_user:
          title: Is Old User
          type: boolean
        user_id:
          title: User Id
          type: string
        hmac:
          title: Hmac
          type: string
        token:
          title: Token
          type: string
        subscription:
          title: Subscription
          type: string
        start_date:
          title: Start Date
          type: string
          format: date-time
        redirect_after_login:
          title: Redirect After Login
          type: string
        is_admin:
          title: Is Admin
          type: boolean
          default: false
    UserOut:
      title: UserOut
      required:
      - email
      - first_name
      - last_name
      - unique_key
      - is_active
      type: object
      properties:
        email:
          title: Email
          type: string
        first_name:
          title: First Name
          type: string
        last_name:
          title: Last Name
          type: string
        unique_key:
          title: Unique Key
          type: string
        profile_image:
          title: Profile Image
          type: string
        trading_challenge:
          title: Trading Challenge
          type: string
        description:
          title: Description
          type: string
        is_active:
          title: Is Active
          type: boolean
        user_type:
          title: User Type
          type: string
        meta_data:
          title: Meta Data
          type: string
        created_at:
          title: Created At
          type: string
          format: date-time
