openapi: 3.2.0
info:
  title: Level2 Hub Controller Deactivate Email API
  version: 0.1.0
tags:
- name: Deactivate Email
paths:
  /deactivate_email:
    get:
      summary: Deactivate Email
      operationId: deactivate_email_deactivate_email_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Deactivate Email
