openapi: 3.2.0
info:
  title: Level2 Hub Controller Save Strategy API
  version: 0.1.0
tags:
- name: Save Strategy
paths:
  /save_strategy:
    post:
      summary: Save Strategy
      operationId: save_strategy_save_strategy_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_save_strategy_save_strategy_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Save Strategy
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_save_strategy_save_strategy_post:
      title: Body_save_strategy_save_strategy_post
      required:
      - keygen
      - strategy_name
      - strategy_data
      - canvas_data
      type: object
      properties:
        keygen:
          title: Keygen
          type: string
        strategy_name:
          title: Strategy Name
          type: string
        strategy_data:
          title: Strategy Data
          type: string
        canvas_data:
          title: Canvas Data
          type: string
