openapi: 3.2.0
info:
  title: Level2 Hub Controller Trading Challenge Email API
  version: 0.1.0
tags:
- name: Trading Challenge Email
paths:
  /trading_challenge_email:
    get:
      summary: Tcemail
      operationId: tcemail_trading_challenge_email_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
      tags:
      - Trading Challenge Email
