openapi: 3.2.0
info:
  title: Level2 Hub Controller Trading Challenge Ww API
  version: 0.1.0
tags:
- name: Trading Challenge Ww
paths:
  /trading_challenge_ww:
    get:
      summary: Tcww
      operationId: tcww_trading_challenge_ww_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
      tags:
      - Trading Challenge Ww
