openapi: 3.2.0
info:
  title: Level2 Hub Controller Forex Rates API
  version: 0.1.0
tags:
- name: Forex Rates
paths:
  /forex_rates:
    get:
      summary: Forex Rates
      operationId: forex_rates_forex_rates_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Forex Rates
