openapi: 3.2.0
info:
  title: Level2 Hub Controller Update Live Order API
  version: 0.1.0
tags:
- name: Update Live Order
paths:
  /update_live_order:
    post:
      summary: Update Live Order
      operationId: update_live_order_update_live_order_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Update Live Order
